@startuml
'https://plantuml.com/activity-diagram-beta

start
:StartingState;
if (isGrounded) then (true)
  :ChangeState(Grounded);
  if (isForward?) then (no)
    :Process controls;
    if (continue processing?) then (no)
      stop
    endif

    if (isPost?) then (yes)
      :Page.onPost();
    else (no)
      :Page.onGet();
    endif
    :Page.onRender();
  endif
else (false)
    

stop

@enduml
